title: "Bushtit Lab"
name: "Bushtit Lab"
url: "https://bushtit.github.io"
description: "A group for iOS and Mac developers who want to explore all that’s new and fascinating in Cocoa development."
copyright: "Bushtit Lab • 2007-2018"
copyright_full: "Copyright (c) 2007-2018 Bushtit Lab. All rights reserved"

author: "Elias Abel"
author_short: "Elias"
author_avatar: "/assets/image/avatar/default_s.jpg"
other_avatar: "/assets/image/avatar/other_avatar.jpg"
author_description: "Software developer on PC, Linux, Android, iOS and OS X platform. Crafty. Blogger. Traveller. Big fan of Apple. Love of color. Doggies are my fave."

email: "admin@meniny.cn"
mail_link: "Mailto:admin@meniny.cn?Subject=Hello&nbsp;there!"
twitter: "https://twitter.com/_Meniny"
github: "https://github.com/Bushtit"
oschina: "https://git.oschina.net/meniny"
appstore: "https://itunes.apple.com/cn/developer/shenyi-li/id1026495349"

exclude: ['Gemfile.lock', 'Gemfile', 'Rakefile']

highlighter: rouge
#pygments
markdown: kramdown
permalink: /posts/:title/
blog_perma: "https://bushtit.github.io/posts"
# Plugins
plugins: [jekyll-paginate,jekyll-toc,liquid,jekyll-asciidoc]
# Gems
gems: [jekyll-paginate,jekyll-toc,liquid,jekyll-asciidoc]
paginate: 5
paginate_path: "/posts/page/:num"
